# 应用基础配置
app:
  name: gin-template # 应用名称
  env: production  # 应用环境，可选: development, testing, production
  port: 8080 # 应用监听的端口
  debug: false # 是否开启Debug模式，开启后会输出更多日志

# 数据库配置
database:
  driver: mysql # 数据库类型，例如: mysql, postgres, sqlite
  host: ${DB_HOST:-localhost}     # 数据库主机地址，优先从环境变量 DB_HOST 获取，若未设置则默认为 localhost
  port: ${DB_PORT:-3306}          # 数据库端口，优先从环境变量 DB_PORT 获取，若未设置则默认为 3306
  username: ${DB_USER:-root}      # 数据库用户名，优先从环境变量 DB_USER 获取，若未设置则默认为 root
  password: ${DB_PASSWORD:-w123}        # 数据库密码，优先从环境变量 DB_PASSWORD 获取
  dbname: ${DB_NAME:-my_database}     # 数据库名称，优先从环境变量 DB_NAME 获取
  max_open_connections: 100 # 数据库最大连接数
  max_idle_connections: 20 # 数据库最大空闲连接数
  connection_max_lifetime: 300s # 连接可复用的最大时间

# 未来可根据需求添加配置，如Redis、MinIO等配置